[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "strip"
sparse_mode = false
build_info = true
extra_output = ["storageLayout", "metadata"]

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Testing
verbosity = 2
fuzz = { runs = 1000, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false, dictionary_weight = 40, include_storage = true, include_push_bytes = true }

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@erc721a/contracts/=lib/ERC721A/contracts/",
    "@solady/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/",
    "@chainlink/=lib/chainlink/",
]

# Profile for CI/CD with stricter settings
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }
verbosity = 4

# Profile for gas optimization
[profile.intense]
optimizer = true
optimizer_runs = 1000000
via_ir = true