name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag version (e.g. v0.1.0)"
        required: true
        type: string
      release_name:
        description: "Release title (defaults to tag)"
        required: false
        type: string
      draft:
        description: "Create as draft"
        required: false
        default: false
        type: boolean
      prerelease:
        description: "Mark as prerelease"
        required: false
        default: false
        type: boolean

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog (last 100 commits)
        id: changelog
        run: |
          echo "## Changes" > CHANGELOG_SNIPPET.md
          echo >> CHANGELOG_SNIPPET.md
          git log -n 100 --pretty=format:"- %s (%h)" >> CHANGELOG_SNIPPET.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name || inputs.tag_name }}
          body_path: CHANGELOG_SNIPPET.md
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
